/***********************************************************************/
/*                                                                     */
/*  FILE        :REMON_3.c                                             */
/*  DATE        :Sat, Nov 25, 2023                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :62P                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

/* ?D??x?p??(priority inheritance), ?D??x???(priority ceiling)???X??icb.h 15?s??? */

/* ?C???N???[?h?t?@?C?? */
#include "sfr62p.h"			/* OAKS16?p??`?t?@?C?? */
#include "REMON.h"
#include "icb.h"
#include "task.h"
#include "dispatcher.h"
#include "semaphore.h"



/* ?v???g?^?C?v?? */
void	main(void);			/* ???C?????	*/

void task0(void);
void task1(void);
void task2(void);
void task3(void);
void task4(void);
void task5(void);
void task6(void);
//void task7(void);

#define PORTIN	0x00
#define PORTOUT 0xff


#define HIGHEST_PRIORITY 0x01
#define MIDDLE_HIGH_PRIORITY 0x02
#define MIDDLE_LOW_PRIORITY 0x04
#define LOWEST_PRIORITY 0x08


#define TASK0 0x01
#define TASK1 0x02
#define TASK2 0x04
#define TASK3 0x08
#define TASK4 0x10
#define TASK5 0x20
#define TASK6 0x40
#define MAIN  0x80


#define WAI_SEM 0x01
#define SIG_SEM 0x02
#define TIME_STOP 0x00



/* ?_?~?[?????p????^?}?N????` */
#define dummy_work(a, b, c, d, count1, count2, num, port1, port2, value1, value2) \
	for((count1) = (num) ; (count1) ; (count1)--){			\
		for((count2) = (num) ; (count2) ; (count2)--){		\
			(d) = (c) / (b);				\
			(d) = (d) / (a);				\
			_asm("\tnop");					\
			_asm("\tnop");					\
			_asm("\tnop");					\
			_asm("\tnop");					\
			port1 = (value1);				\
			_asm("\tnop");					\
			_asm("\tnop");					\
			_asm("\tnop");					\
			_asm("\tnop");					\
			port2 = (value2);				\
	 		_asm("\tnop");					\
			_asm("\tnop");					\
			_asm("\tnop");					\
			_asm("\tnop");					\
		}									\
	}

///////////////////////////////////////////////

void main(void)
{						
	_asm( "\tFCLR	I");			/* ???????~						*/

	p0 = 0x00;						/* ?|?[?g1?f?[?^??????				*/
	pd0 = PORTOUT;					/* ?|?[?g1?o????					*/
		
	p1 = 0x00;						/* LED?p?|?[?g1?f?[?^??????			*/
	pd1 = PORTOUT;					/* LED?p?|?[?g1?o????				*/
	
	p2 = 0x00;						/* ???W?b?N?A?i???C?U?p?|?[?g2?f?[?^??????	*/
	pd2 = PORTOUT;					/* ???W?b?N?A?i???C?U?p?|?[?g2?o????		*/

	ini_tsk();
	ini_sem();

	cre_tsk((unsigned short)0, (unsigned long)task0);
	cre_tsk((unsigned short)1, (unsigned long)task1);
	cre_tsk((unsigned short)2, (unsigned long)task2);
	cre_tsk((unsigned short)3, (unsigned long)task3);
	cre_tsk((unsigned short)4, (unsigned long)task4);
	cre_tsk((unsigned short)5, (unsigned long)task5);
	cre_tsk((unsigned short)6, (unsigned long)task6);
	//cre_tsk((unsigned short)7, (unsigned long)task7);

	_asm( "\tFSET	I");			/* ?????????						*/
	
	//p2 = MAIN;
	
	sta_tsk((unsigned short)1);
	/*
	sta_tsk((unsigned short)1);
	sta_tsk((unsigned short)2);
	sta_tsk((unsigned short)3);
	sta_tsk((unsigned short)4);
	sta_tsk((unsigned short)5);
	sta_tsk((unsigned short)6);
	*/
	
	//p2 = MAIN;

	for (;;) {		// ????????????i?f?o?b?O?p?j
		unsigned int i;
		p0 ^= 0x01;
		for (i = 0xFFFFF; i; --i);
	}
	
	/* dummy_work()?p??? */
	/*volatile long a = 3;
	volatile long b = 7;
	volatile long c = 21;
	volatile long d;
	volatile long i, j;
	
	dummy_work(a, b, c, d, i, j, DUMMY_NUM, p1, p2, 0xa5, TASK0);*/
}



void task0(void) /* Highest Priority */
{
	wai_sem((unsigned short) 0);
	sig_sem((unsigned short) 0);
	ext_tsk();
}

void task1(void) /* Middle Priority */
{
	wai_sem((unsigned short) 0);
	sta_tsk((unsigned short)0);
	sig_sem((unsigned short) 0);
	ext_tsk();	
}

void task2(void) /* Middle Priority */
{
	p2 = TASK2;
	ext_tsk();	
}

void task3(void)
{
	p2 = TASK3;
	ext_tsk();
}

void task4(void)
{
	p2 = TASK4;
	wai_sem((unsigned short) 1);
	sig_sem((unsigned short) 1);	
	ext_tsk();
}

void task5(void)
{
	p2 = TASK5;
	ext_tsk();
}

void task6(void) 
{
	p2 = TASK6;
	ext_tsk(); 
}
